---
title: "other-other-page"
format: html
---

```{r}
library(ggplot2)
library(tidyverse)
library(plotly)
```

## Plotting mean sentence length over time plot with a bar chart

```{r}
# ggplot(inaug_speeches_master, aes(x = date, y = meanSentenceLength, fill = meanSentenceLength)) +
#   geom_col(show.legend = FALSE) +
#   scale_fill_gradient2(low = "#d61106", mid = "#d6d6d6", high = "#05853c", midpoint = 0) + 
#   labs(
#     title = "Mean Sentence Length of Inaugural Speeches",
#     x = "Year",
#     y = "Mean Sentence Length"
#   ) +
#   theme_minimal()


ms <- ggplot(inaug_speeches_master, aes(
  x = date, y = meanSentenceLength,
  text = paste("President:", president,
               "<br>Year:", date,
               "<br>Mean Sentence Length:", round(meanSentenceLength, 3)),
  fill = meanSentenceLength)) +
  geom_col(show.legend = FALSE) +
  scale_fill_gradient2(low = "#d61106", mid = "#d6d6d6", high = "#05853c", midpoint = 0) + 
  labs(
    title = "Mean Sentence Length of Inaugural Speeches",
    x = "Year",
    y = "Mean Sentence Length"
  ) +
  theme_minimal()

ggplotly(ms, tooltip = "text")


## Plotting readability/Flesh-Kincaid over time plot with a bar chart

# ggplot(inaug_speeches_master, aes(x = date, y = Flesch.Kincaid, fill = Flesch.Kincaid)) +
#   geom_col(show.legend = FALSE) +
#   scale_fill_gradient2(low = "#d61106", mid = "#d6d6d6", high = "#05853c", midpoint = 0) + 
#   labs(
#     title = "Flesh-Kincaid score of Inaugural Speeches",
#     x = "Year",
#     y = "Flesh-Kincaid score"
#   ) +
#   theme_minimal()


fk <- ggplot(inaug_speeches_master, aes(
  x = date, y = Flesch.Kincaid,
  text = paste("President:", president,
               "<br>Year:", date,
               "<br>Flesch.Kincaid:", round(Flesch.Kincaid, 3)),
  fill = Flesch.Kincaid)) +
  geom_col(show.legend = FALSE) +
  scale_fill_gradient2(low = "#d61106", mid = "#d6d6d6", high = "#05853c", midpoint = 0) + 
  labs(
    title = "Flesch-Kincaid score of Inaugural Speeches",
    x = "Year",
    y = "Flesch-Kincaid score"
  ) +
  theme_minimal()

ggplotly(fk, tooltip = "text")



# Top 5 presidents with the hardest inaugural speech (highest Flesch-Kincaid score)
 
 top5_highpress <- inaug_speeches_master |>
  arrange(desc(Flesch.Kincaid)) |>
  select(president, date, Flesch.Kincaid) |>
  slice_head(n = 5)
top5_highpress
 
 
# Top 5 Presidents with the easiest inaugural speech (lowest Flesch-Kincaid score)
 top5_lowpress <- inaug_speeches_master |>
  arrange(Flesch.Kincaid) |>
  select(president, date, Flesch.Kincaid) |>
  slice_head(n = 5)
top5_lowpress

top5_press <- full_join(top5_highpress, top5_lowpress)

 
 # table displaying the top 5 presidents with the highest Flesch-Kincaid score 

 top5_lowpress |>
  kable(booktabs = TRUE, 
        digits = 2,
        col.names = c("President", "Year", "Flesch-Kincaid Score")) |>
  kable_styling()

 
  # table displaying the top 5 presidents with the lowest Flesch-Kincaid scores 
 
  top5_highpress |>
  kable(booktabs = TRUE, 
        digits = 2,
        col.names = c("President", "Year", "Flesch-Kincaid Score")) |>
  kable_styling()
  
  
```


```{r}
# Mean Sentence Length vs. Sentiment

#| label: Plotting-Flesch-Kincaid-vs-Sentiment


# Make sure to set seed for reproducibility!
set.seed(100)

msl_kmeans_results <- inaug_speeches_master |> 
  # Can only include numeric variables that we are clustering by
  select(meanSentenceLength, sentiment_avg) |> 
  kmeans(centers = 6, nstart = 10) 

# Check named elements of object
names(msl_kmeans_results)

# Centroids
msl_kmeans_results$centers

# Cluster sizes
msl_kmeans_results$size


# Join cluster assignments with original dataset (requires the broom package)
msl_clustered <- msl_kmeans_results |> 
  augment(inaug_speeches_master) |> 
  mutate(cluster_2 = factor(.cluster))

# Make dataframe out of estimated cluster centroids
msl_cluster_centers <- msl_kmeans_results$centers |>
  as_tibble() |> 
  mutate(cluster_2 = factor(row_number()))

# Plot cluster assignments and centroids
ggplot(msl_clustered, aes(x = sentiment_avg, y = meanSentenceLength)) +
  geom_point(aes(color = cluster_2), alpha = 0.6)  + 
  geom_label(data = msl_cluster_centers, 
             aes(label = cluster_2), 
             size = 3) + 
  theme_classic() +
  theme(legend.position = "none") 



MS_s <- ggplot(msl_clustered, aes(x = meanSentenceLength, y = sentiment_avg)) +
  geom_point(aes(color = cluster_2, 
                 text = paste( "President", president,
                              "<br>Sentiment:", sentiment_avg,
                              "<br>Mean Sentence Length:", meanSentenceLength,
                              "<br>Cluster:", cluster_2)), 
             alpha = 0.6) +
  geom_label(data = msl_cluster_centers, 
             aes(label = cluster_2, 
                 text = paste("Cluster Center:", cluster_2)), 
             size = 3) +
  labs(y = "Average Sentiment Score",
       x = "Mean Sentence Length",
        title = "Inaugural Address Analysis",
       caption = "Average Sentiment Score vs Mean Sentence Length",
       color = "Cluster") +
  theme_minimal()

ggplotly(MS_s, tooltip = "text")


```

```{r}
#| label: Mean Sentence Length-vs-Year
 
msle <- ggplot(inaug_speeches_master, aes(x = date, y = meanSentenceLength,
                                       text = paste("President:", 
                                                    president,
                                                    "<br>Year:", 
                                                    date,
                                                    "<br> Mean Sentence Length:",
                                                    meanSentenceLength))
            ) +
  geom_point() +
  geom_smooth( method = "loess", se = TRUE)+
  scale_x_continuous(breaks = scales:: breaks_width(25), minor_breaks = NULL) +
  labs(title = "Inagural Speech Complexity Over Time",
    y = "Mean Sentence Length",
       x = "Year") +
  theme_minimal()

ggplotly(msle, tooltip = "text")
```


```{r}

sec_terms <- inaug_speeches_master |>
  select(president, term, sentiment_avg) |>
  pivot_wider(names_from = term, 
              values_from = sentiment_avg, 
              names_prefix = "") |>
  rename(first_term = `1st Term`,
         second_term = `2nd Term`,
         third_term = `3rd Term`,
         fourth_term = `4th Term`) |>
  select(-third_term, -fourth_term) |>
  rename(sent_first = `first_term`,
         sent_second = `second_term`) |>
  filter(!is.na(sent_second))


sec_terms2 <- inaug_speeches_master |>
  select(president, term, Flesch.Kincaid) |>
  pivot_wider(names_from = term, 
              values_from = Flesch.Kincaid, 
              names_prefix = "") |>
  rename(first_term = `1st Term`,
         second_term = `2nd Term`,
         third_term = `3rd Term`,
         fourth_term = `4th Term`) |>
  select(-third_term, -fourth_term) |>
    rename(fk_first = `first_term`,
         fk_second = `second_term`) |>
  filter(!is.na(fk_second))

# joining both datasets

sec_terms_sent_fk <- left_join(sec_terms, sec_terms2, by = "president")

```



```{r}
# Inaugural Address Complexity Change from First to Second Term for presidents that served two terms
q <- ggplot(sec_terms_sent_fk, aes(x = fk_first, y = fk_second,
                                   text = paste("President:", 
                                                    president,
                                                    "<br> 1st Term FK Score:",
                                                    fk_first,
                                                "<br> 2nd Term FK Score:",
                                                fk_second))) +
  geom_point(aes(color = president, size = 0.1)) + 
  labs(title = "Inaugural Address Complexity Change from First to Second Term",
       x = "First Term Flesch-Kincaid Score",
       y = "Second Term Flesch-Kincaid Score") +
  theme_minimal()

ggplotly(q, tooltip = "text") |>
  layout(showlegend = FALSE)
```

```{r}
# Inaugural Address Complexity Change from First to Second Term for presidents that served two terms
q <- ggplot(sec_terms_sent_fk, aes(x = sent_first, y = sent_second,
                                   text = paste("President:", 
                                                    president,
                                                    "<br> 1st Term Sentiment Score:",
                                                    round(sent_first, 3),
                                                "<br> 2nd Term Sentiment Score:",
                                                round(sent_second, 3) ) )) +
  geom_point(aes(color = president, size = 0.1)) + 
  labs(title = "Inaugural Address Sentiment Change from First to Second Term",
       x = "First Term Sentiment Avg",
       y = "Second Term Sentiment Avg") +
  theme_minimal()

# Removing the legend 
ggplotly(q, tooltip = "text") |>
  layout(showlegend = FALSE)


```














